src/event-loop.lisp
test/pipe.lisp

No longer enter infinite loop when there are handles that cannot be
closed for some reason. Do at most 100000 iterations, then show
warning and dump currently active handles.
I encounter event loop shutdown problems from time to time
and this will perhaps be of some help with debugging.
PIPE-CONNECT-FAIL was probably hanging due to HANDLE-TYPE
problem in cl-libuv, see orthecreedence/cl-libuv#3

Improve event loop shutdown diagnostics, reenable PIPE-CONNECT-FAIL test.

---

src/socket.lisp
test/tcp.lisp

Flushing socket buffer before closing is perhaps the right thing to do unless FORCE argument is true.
Also, START/END handling was broken in STREAMISH-WRITE implementation for sockets when *BUFFER-WRITES* was true.

More *BUFFER-WRITES* related fixes.

---

src/tcp.lisp

Sometimes dns-lookup callback may be invoked during event loop shutdown
or after the socket was explicitly closed. That led to
`!uv__io_active(&stream->io_watcher, UV__POLLIN | UV__POLLOUT)`
(stream.c) assertion errors in libuv due to `uv_tcp_connect()`
call on the socket.

Safeguard against late dns-lookup connect callbacks during event loop shutdown

---

src/ssl/tcp.lisp

This fixes the issue reported in https://github.com/orthecreedence/cl-async/issues/126

working ssl

---

src/dns.lisp
src/package.lisp
src/util/foreign.lisp
test/dns.lisp

This is a fairly straightforward export of [uv_getnameinfo](http://docs.libuv.org/en/latest/dns.html#c.uv_getnameinfo), similar to `dns-lookup`.
`reverse-dns-lookup` makes the callback be called with HOST and SERVICE arguments, but the service argument after this change will always be "0", so it should probably just be dropped. [This patch](https://github.com/orivej/cl-async/commit/4967631ee83c2e44d3e566e5697b18654d172b6d) adds the port argument (to look service name from `/etc/services` on Linux), but somehow the port number used for lookup is the specified port times 256. I also don't see any use in bundling HOST resolution and SERVICE name resolution in the same function.

Add reverse-dns-lookup

---

src/async-stream.lisp

At [this line](https://github.com/orthecreedence/cl-async/blob/master/src/async-stream.lisp#L102) in stream-read-sequence, you're doing `(subseq buffer start <end>)`, but `start` is an index into the output sequence, not an index into the internal stream buffer. This causes problems when trying to fill a large sequence from multiple reads on a tcp connection.
This branch fixes that and cleans the function up a little. There should be a small performance increase, since the new version doesn't cons up an intermediate sequence to copy into the output. You could get more out of it by storing a read cursor in the stream instead of using `subseq` on the internal buffer, but that's a bit more involved.
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on …

Stream read sequence

---

src/ssl/tcp.lisp

So that `close-ssl` can close it properly.

Save the ad-hoc SSL context when connecting to a server

---

src/dns.lisp
src/streamish.lisp
test/dns.lisp

Some stale data are kept in `*data-registry*` and `*function-registry*`, causing memory leaks. This PR tries to fix them.
I was able to track down two leaking spots in `dns.lisp` and one in `streamish.lisp`, all related to the **pointer data** infrastructure. In this PR I wrote tests for the DNS cases, but didn't figure out how to properly test the case in `streamish.lisp`.

Pointer data mem leak

---

src/ssl/tcp.lisp

Hey Andrew,
I am using a tweaked version of https://github.com/TBRSS/cl-stripe-client which uses your drakma-async and Stripe sent me an email saying I needed to migrate from TLS 1.0 to TLS 1.2 (see https://support.stripe.com/questions/how-do-i-upgrade-my-stripe-integration-from-tls-1-0-to-tls-1-2).
I tracked the issue down to ssl/tcp.lisp in cl-async-ssl where the call to `create-ssl-ctx` in `tcp-ssl-connect-new` was explicitly specifying `:tlsv1-client`.  My limited googling (http://stackoverflow.com/questions/23709664/openssl-let-the-server-and-client-negotiate-the-method) makes me think this is not the best default choice, and indeed `create-ssl-ctx` itself seems to have a better default,  So this pull request is just to use the default of `:sslv23`.  
This makes Stripe happy now but …

Use default :method  in calling create-ssl-ctx in tcp-ssl-connect-new

---

src/ssl/tcp.lisp

Looks like `key` should be loaded here instead of `certificate`

Fix private key path in tcp-ssl-server-new

---

src/ssl/package.lisp
src/ssl/tcp.lisp

I started to work on a fix for #154.
It seems that initialisation rules for SSL changed with version 1, see:
https://wiki.openssl.org/index.php/Library_Initialization
unfortunately the library version number is not static data but is hidden in a macro. Using this patch we can `(ql:quickload "cl-async-ssl") in Debian Stretch for instance. However the library does not seem to be correctly initialised because the following code fails with
```
Error: #<TCP-SSL-ERROR NIL: 336236705: error creating SSL context: library has no ciphers {1002489F13}>
```
``` lisp
(ql:quickload "drakma-async")
(defun my-http-request ()
(blackbird:catcher
(blackbird:multiple-promise-bind (body status headers)
(das:http-request "https://www.google.com/")
(format t "Status: ~a~%" status)
(format t "Headers: ~s~%" …
```

WIP Acknowledge init change for libssl 1

---

src/socket.lisp

It's good to have stream available when server needs to communicate first after client connects. The connect-cb already works this way for outgoing sockets.

Expose stream to incoming sockets

---

src/ssl/package.lisp

OpenBSD fails to load provided libcrypto/ssl libraries when loading cl-async-ssl system.
The current version numbers are woefully outdated, ( 20.1 vs. 45.1 in currently used).
Easy fix would be to update the version numbers to match currently used numbers but the library will break as soons as libressl bumps versions. And how long list of version numbers should be kept in cl-async-ssl?
I think best option would be to make the code look for "libssl.so" and "libcrypto.so" libraries. This makes the OpenBSD linker to load the matching library with biggest major.minor version. This is often the right thing to do. I doubt theres enough OpenBSD Common Lisp hackers to keep hardcoded version numbers in sync.

try to load latest ssl/crypto libraries on OpenBSD

---

src/ssl/package.lisp

LibreSSL has different version numbering, so while libssl uses the `libssl.so`, there's no such case for `libcrypto` which is `libcrypto.so.44.0.1` with libressl. This is the same SSL library that OpenBSD uses, some linux distributions use it too.

Make SSL work with libressl on linux

---

src/pipe.lisp
src/process.lisp
test/process.lisp

The call to `write-pending-socket-data` in `spawn` triggers a `streamish-broken-pipe` error (when attempting to write to stdout and stderr streams) which breaks tests.
Data provided through the `:data` argument to the stdin container is flushed at <https://github.com/orthecreedence/cl-async/blob/master/src/socket.lisp#L276> meaning that the call can be removed altogether.
I have also removed what seems to be a spurious `defclass` in `pipe.lisp`

improved spawn

---

src/fsevent.lisp
src/package.lisp
src/process.lisp
src/streamish.lisp
src/util/helpers.lisp
test/dns.lisp
test/fsevent.lisp
test/process.lisp

All tests now run on my system and hopefully everywhere else too.
Summary of changes:
* according to the libuv docs the `UV_FS_EVENT_RECURSIVE` flag is not supported on linux. However to my pleasant surprise, providing 0 worked on directories anyways.
* fixed improperly indented doc line from my previous pull req
* use `alexandria:ensure-list` in `util/helpers.lisp`
* google's public dns has changed
* fixed `fs-monitor` test - after fixing the flag issue, the problem was that the fs handle was keeping the loop alive, causing a timeout. Also removed possibly spurious `as:delay` surrounding the checking code.
This closes <https://github.com/orthecreedence/cl-async/issues/139> and <https://github.com/orthecreedence/cl-async/issues/137>. Also note that …

fixed all tests on x86 GNU/voidlinux

---

src/streamish.lisp

Without this, if an error on `streamish` occurs and there is no method for that errno specifically, it falls through to the default method which creates `even-error` and reference to the `streamish` is lost (for the client code).
I discovered this by accident: my cl-async server worked mostly fine, but every 1000 or so connections I got 113 EHOSTUNREACH error and in the client code I could not retrieve on which of the open sockets this had happened, because the `event-cb` already got it as instance of `event-error`.
It should be mostly backwards compatible, except at https://github.com/orthecreedence/cl-async/blob/f6423e44404a44434d803605e0d2e17199158e28/src/streamish.lisp#L25-L27 the callback would be executed with as:delay instead of directly. I don't understand why the delay is there …

when streamish is provided, always create stramish-error instead of event-error

---

src/streamish.lisp

The breakage was caused by a call to write-to-uvstream which specified
both :start and :end as NIL.
Unfortunately, it was easier to alter write-to-uvstream than change
the calling code.
For the reference, the test report looked like this:
```
Running test suite CL-ASYNC-TEST-CORE
Running test DATA-POINTERS .
Running test IPV4-ADDRESS ..........
Running test IPV6-ADDRESS ............
Running test POINTER-CALLBACKS ...
Running test POINTER-DATA ...
Running test EVENT-LOOP-STARTS .
Running test EVENT-LOOP-EXIT .
Running test CATCH-APP-ERRORS ..
Running test DATA-AND-FN-POINTERS ..
Running test EXIT-CALLBACKS .
Running test DELAY-SIMPLE .
Running test DELAY-TIMER .
Running test DELAY-MULTI ...
Running test INTERVAL .
Running test DNS-SIMPLE .
Running test DNS-MULTI ..
Running test …
```

Fixed most of broken tests

---

src/ssl/package.lisp

Hello!
While trying to package cl-async using application with [Shinmera's deploy](https://github.com/Shinmera/deploy), I was getting error regarding libeay32 library (deploy forces all cffi libraries to be present as files). Looks like libeay32 is only required on Windows, so this PR removes dependency on that library under non-Windows OSes.

Do not require libeay32 under non-Windows OSes

---

src/dns.lisp
src/package.lisp
src/ssl/package.lisp
src/ssl/tcp.lisp
src/ssl/util.lisp
src/streamish.lisp
test/pipe.lisp
test/tcp-ssl.lisp

There are five changesets here.  The first four fix existing test failures to avoid needing to handwave test failures with the fifth patch -- the actual fix.
The main event (f0cc925), formalizes the patch suggested in issue #188.  This provides backward compatibility with OpenSSL 1.0.1 where the patch in the bug report does not.  Arguably, providing compatibility with old and probably broken OpenSSL versions is not doing anyone any favors.  But this seems a more complete solution.
This has been tested with `(cl-async-test::run-tests :ssl t)` on Linux with the following OpenSSL and SBCL versions:
| distribution | OpenSSL version | SBCL version |
| --- | --- | --- |
| debian-08  | 1.0.1t | 1.2.4.debian |
| debian-09 | 1.1.0l | 1.3.14.debian |
| debian-11 | 1.1.1k | 2.1.1.debian |

Fix for issue #188

---

examples/dns-lookup.lisp

The callback is a keyword element now.
Also simplified some of the default parameter handling to focus the code on as:dns-lookup.

docs: fix examples/dns-lookup.lisp

---

cl-async.asd
src/streamish.lisp
src/util/helpers.lisp

Remove the `:serial t` component, which is not necessary because of the specific dependencies in the `:components` and fix the dependency for the `"dns"` component.
Fixes issue #194

Fix cl-async ASDF definition.

---

src/util/helpers.lisp

Re-implement this by making a new class for the "alias" that inherits from the parent. This is no longer really aliasing, but at least SBCL's compiler really dislikes the original implementation of this macro.
Addresses #193

Redefine DEFINE-CONDITION-ALIAS.

---

src/signal.lisp
src/util/error.lisp
src/util/foreign.lisp

Quiets a bunch of compiler warnings.

Remove defs of variables that are never read.

---

src/ssl/tcp.lisp

The function accepts an `uint64` as its first argument and a pointer as the second one, and passing `:int 0` for both has been causing issues on 32-bit systems

Use the proper signature for OPENSSL_init_ssl function call

---

src/ssl/tcp.lisp
src/ssl/util.lisp

I had a server reject TLS connections that didn't carry an SNI extension.
I've only added enough to include the SNI extension, it's copied nearly verbatim from CL+SSL.

Added SNI calls to socket setup when we have hostname.
